version: '3.8'

services:
  server:
    container_name: library-helper
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
        POSTGRES_DB: spring
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    ports:
      - '5432:5432'